<a href="https://colab.research.google.com/github/pmukeshreddy/pytorch-basics/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
x = torch.empty(3)
x1 = torch.empty(4,3)
x2 = torch.empty(2,2,3)
print(x)
print(x1)
print(x2)

tensor([1.6972e-35, 0.0000e+00, 1.5975e-43])
tensor([[1.6972e-35, 0.0000e+00, 3.9236e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3556e-19, 8.6462e+11, 3.2778e+09],
        [1.4988e+10, 3.2522e+03, 1.3023e+01]])
tensor([[[1.6973e-35, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [7]:
r = torch.rand(2,2)
print(r)
z = torch.zeros(2,2)
print(z)

tensor([[0.5433, 0.3957],
        [0.0263, 0.4899]])
tensor([[0., 0.],
        [0., 0.]])


In [9]:
o = torch.ones(2,2,dtype=torch.int)
print(o)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [10]:
print(x2.size())

torch.Size([2, 2, 3])


In [12]:
g = torch.tensor([12,1.2,3.4])
print(g)

tensor([12.0000,  1.2000,  3.4000])


Addition 

In [14]:
q = torch.rand(2,2)
w = torch.rand(2,2)
e = q + w
#or
e = torch.add(q,w)
print(q)
print(w)
print(e)

tensor([[0.0046, 0.7482],
        [0.2406, 0.1699]])
tensor([[0.3293, 0.5965],
        [0.9623, 0.3699]])
tensor([[0.3339, 1.3447],
        [1.2029, 0.5398]])


In [15]:
#inpalce addtion

w.add_(q)
print(w)

tensor([[0.3339, 1.3447],
        [1.2029, 0.5398]])


subtraction

In [18]:
s = q - w
#or
s = torch.sub(q,w)
print(s)

w.sub_(q)
print(w)

tensor([[-0.3247,  0.1517],
        [-0.7218, -0.2001]])
tensor([[ 0.3247, -0.1517],
        [ 0.7218,  0.2001]])


multiplication

In [19]:
mul = q * w
mul = torch.mul(q,w)
print(mul)
w.mul_(q)
print(w)

tensor([[ 0.0015, -0.1135],
        [ 0.1736,  0.0340]])
tensor([[ 0.0015, -0.1135],
        [ 0.1736,  0.0340]])


divsion


In [20]:
d = q / w
d = torch.div(q,w)
print(d)
w.div_(q)
print(w)

tensor([[ 3.0794, -6.5937],
        [ 1.3855,  4.9985]])
tensor([[ 0.3247, -0.1517],
        [ 0.7218,  0.2001]])


slicing

In [26]:
sl = torch.rand(5,3)
print(sl)
print(sl[:,0])
print(sl[1,:])
print(sl[1,1].item())

tensor([[0.9869, 0.6642, 0.8112],
        [0.9666, 0.6724, 0.3580],
        [0.2634, 0.7835, 0.6053],
        [0.3982, 0.2667, 0.6452],
        [0.2215, 0.6034, 0.4739]])
tensor([0.9869, 0.9666, 0.2634, 0.3982, 0.2215])
tensor([0.9666, 0.6724, 0.3580])
0.67238849401474


reshaping

In [31]:
q1 = torch.rand(4,4)
w1 = q1.view(16)
print(q1)
print(w1)
w2 = q1.view(-1,4)
print(w2)

tensor([[0.1144, 0.7965, 0.0715, 0.3885],
        [0.2609, 0.9916, 0.2310, 0.6149],
        [0.5869, 0.0236, 0.6287, 0.8211],
        [0.8185, 0.2263, 0.6384, 0.8398]])
tensor([0.1144, 0.7965, 0.0715, 0.3885, 0.2609, 0.9916, 0.2310, 0.6149, 0.5869,
        0.0236, 0.6287, 0.8211, 0.8185, 0.2263, 0.6384, 0.8398])
tensor([[0.1144, 0.7965, 0.0715, 0.3885],
        [0.2609, 0.9916, 0.2310, 0.6149],
        [0.5869, 0.0236, 0.6287, 0.8211],
        [0.8185, 0.2263, 0.6384, 0.8398]])


numpy to torch and vice-versa

In [32]:
import numpy as np

In [35]:
# tensor to numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [38]:
#numpy to tensor
a1 = np.ones(5)
print(a1)
b1 = torch.from_numpy(a1)
print(b1)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
