<a href="https://colab.research.google.com/github/pmukeshreddy/pytorch-basics/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.4717,  0.8860, -1.9249], requires_grad=True)


In [ ]:
y = x + 3
z = x * 2
e = z.mean()
print(y,z,e)

tensor([3.4717, 3.8860, 1.0751], grad_fn=<AddBackward0>) tensor([ 0.9433,  1.7720, -3.8499], grad_fn=<MulBackward0>) tensor(-0.3782, grad_fn=<MeanBackward0>)


In [ ]:
e.backward()
print(x.grad)

tensor([0.6667, 0.6667, 0.6667])


In [ ]:
x = torch.tensor([1.2,3.2,4.5],requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([1.2000, 3.2000, 4.5000], requires_grad=True)
tensor([1.2000, 3.2000, 4.5000])


In [ ]:
x = torch.tensor([1.2,3.2,4.5],requires_grad=True)
print(x)
y = x.detach()
print(y)

tensor([1.2000, 3.2000, 4.5000], requires_grad=True)
tensor([1.2000, 3.2000, 4.5000])


In [ ]:
x = torch.tensor([1.2,3.2,4.5],requires_grad=True)
with torch.no_grad():
  y = x + 2
  print(y)

y = x + 2
print(y)

tensor([3.2000, 5.2000, 6.5000])
tensor([3.2000, 5.2000, 6.5000], grad_fn=<AddBackward0>)


In [ ]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
